# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-aIYnUQGrKpwaJrhztQGDhdYHkUfNcdO
"""

!pip -q install lightgbm==4.3.0 ta==0.11.0 --upgrade pandas

from pathlib import Path
import pandas as pd, numpy as np, matplotlib.pyplot as plt
plt.rcParams["figure.dpi"] = 120          # 图像清晰一点

# 把 CSV 放在  /content/drive/MyDrive/qqq_project/data/raw  下
PRICE_CSV = "data/raw/qqq_hourly_2018_2023.csv"
NEWS_CSV  = "data/raw/news_sentiment_2018-2023.csv"

assert Path(PRICE_CSV).exists() and Path(NEWS_CSV).exists(), "✔️ 先把两个 CSV 放好再跑"

import ta    # 技术指标库

# ---- 价格 1‑h ----
price = (pd.read_csv(PRICE_CSV, parse_dates=['t'])
           .rename(columns={'t':'datetime'})
           .set_index('datetime')
           .sort_index())

# ---- 新闻情绪：先聚合到 1‑h 均值 & 计数 ----
sent_1h = (pd.read_csv(NEWS_CSV, parse_dates=['datetime'])
             .set_index('datetime')          # 已是 UTC
             .resample('1h')
             .agg({'score':'mean', 'headline':'count'})
             .rename(columns={'score':'sent_score','headline':'n_news'})
          )

# ---- 内连接 & 缺值填充 ----
df = (price.join(sent_1h, how='left')
            .fillna({'sent_score':0, 'n_news':0}))

# ---- 技术因子示例 ----
df['rsi_14'] = ta.momentum.RSIIndicator(df['close']).rsi()
df['atr_14'] = ta.volatility.AverageTrueRange(
                    df['high'], df['low'], df['close']).average_true_range()
df['vol_z']  = (df['volume'] - df['volume'].rolling(24).mean()) / df['volume'].rolling(24).std()
df['ret_1h'] = df['close'].pct_change()
df['ret_24h']= df['close'].pct_change(24)

# 保存特征（可选）
Path("data/work").mkdir(parents=True, exist_ok=True)
OUT_PARQ = Path("data/work/qqq_features_2018_2023.parquet")
df.to_parquet(OUT_PARQ)
print("✅ 特征表保存:", OUT_PARQ, "行:", len(df))

import lightgbm as lgb
from sklearn.metrics import roc_auc_score

START_TRAIN = "2018-01-02"
END_TRAIN   = "2022-12-31"
START_TEST  = "2023-01-01"

# 生成 24h 收益方向标签
horizon = 24
fwd_ret  = df['close'].shift(-horizon)/df['close'] - 1
label    = (fwd_ret > 0).astype(int)

X = df.drop(columns=['close'])           # 价格本身留一列也行
y = label

X_tr, y_tr = X.loc[:END_TRAIN], y.loc[:END_TRAIN]
X_te, y_te = X.loc[START_TEST:], y.loc[START_TEST:]

dtrain = lgb.Dataset(X_tr, y_tr)
param  = dict(objective="binary", metric="auc",
              learning_rate=0.01, num_leaves=63, feature_fraction=0.8,
              verbose=-1, seed=42)

model = lgb.train(param, dtrain,
                  num_boost_round=400,
                  valid_sets=[lgb.Dataset(X_te, y_te)],
                  valid_names=["test"],
                  verbose_eval=100)

auc = roc_auc_score(y_te, model.predict(X_te))
print(f"AUC(2023): {auc:.3f}")

# 概率 → -1/0/1 信号
prob = model.predict(X_te, num_iteration=model.best_iteration)
pos  = 2*prob - 1                      # 映射到 [-1,1]

# (可选) 低波动过滤：VIX 信号例子
# pos *= (df.loc[START_TEST:,'vix'] < 25).astype(int)

ret       = X_te['close'].pct_change().fillna(0)   # 收益率
eq_curve  = (1 + pos * ret).cumprod()

eq_curve.plot(figsize=(10,4), title="Equity Curve (2023 Test)")
print("最终净值:", eq_curve.iloc[-1].round(3))

